# Generated by Django 5.0.1 on 2025-08-27 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('neighbourhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('website', models.URLField(blank=True)),
                ('reservation_url', models.URLField(blank=True)),
                ('menu_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('reservation_partner', models.CharField(choices=[('OpenTable', 'OpenTable'), ('SevenRooms', 'SevenRooms'), ('Tock', 'Tock'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=20)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('vibes', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('price_range', models.CharField(blank=True, choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], default='$$', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
